routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes();

Route::get('/home', ['as'=>'home', 'uses'=>'HomeController@index']);

Route::group(['middleware'=>['auth']], function(){
    Route::resource('category', 'CategoryController');
    Route::get('category/{id}/delete', ['as'=>'category.delete', 'uses'=>'CategoryController@destroy']);

    Route::resource('post', 'PostController');
    Route::get('post/{id}/delete', ['as'=>'post.delete', 'uses'=>'PostController@destroy']);

    Route::resource('media', 'MediaController');
    Route::get('media/{id}/delete', ['as'=>'media.delete', 'uses'=>'MediaController@destroy']);

});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'category_id',
        'title',
        'excerpt',
        'thumbnail',
        'content',
        'total_views',
        'last_viewed'
    ];
    
    public function category(){
        return $this->belongsTo('App\Models\Category');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = Category::all();

        if($request->has('category_id') && $request->get('category_id') != 'all'){
            $rows = Post::where('category_id', $request->get('category_id'))->orderBy('id', 'desc')->paginate(10);
        }else{
            $rows = Post::orderBy('id', 'desc')->paginate(10);
        }

        return view('post.index', ['rows'=>$rows, 'categories'=>$categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('post.create', ['categories'=>$categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'category_id'   =>  'required|integer',
            'title'         =>  'required|string',
            'excerpt'       =>  'required|string',
            'thumbnail'     =>  'image',
            'content'       =>  'required|string'
        ]);

        if($request->hasFile('thumbnail')){
            $fileName = str_random(16) . time() .  '.' . $request->file('thumbnail')->getClientOriginalExtension();
            $request->file('thumbnail')->move('uploads', $fileName);
            $thumbnailPath = 'uploads/' . $fileName;
        }else{
            $thumbnailPath = 'uploads/post-default-thumbnail.jpg';    
        }

        Post::create([
            'category_id'   =>  $request->get('category_id'),
            'title'         =>  $request->get('title'),
            'excerpt'       =>  $request->get('excerpt'),
            'thumbnail'     =>  $thumbnailPath,
            'content'       =>  $request->get('content'),
            'total_views'   =>  0,
            'last_viewed'   =>  Carbon::now()
        ]);

        return redirect(route('post.index'))->with('msg', 'Post is created successfully!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $row = Post::find($id);
        $categories = Category::all();
        return view('post.edit', ['row'=>$row, 'categories'=>$categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'category_id'   =>  'required|integer',
            'title'         =>  'required|string',
            'excerpt'       =>  'required|string',
            'thumbnail'     =>  'image',
            'content'       =>  'required|string'
        ]);

        $post = Post::find($id);

        if($request->hasFile('thumbnail')){
            File::delete($post->thumbnail);
            $fileName = str_random(16) . time() .  '.' . $request->file('thumbnail')->getClientOriginalExtension();
            $request->file('thumbnail')->move('uploads', $fileName);
            $thumbnailPath = 'uploads/' . $fileName;
        }else{
            $thumbnailPath = $post->thumbnail;
        }

        $post->update([
            'category_id'   =>  $request->get('category_id'),
            'title'         =>  $request->get('title'),
            'excerpt'       =>  $request->get('excerpt'),
            'thumbnail'     =>  $thumbnailPath,
            'content'       =>  $request->get('content')
        ]);

        return redirect(route('post.index'))->with('msg', 'Post is updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        File::delete($post->thumbnail);
        Post::destroy($id);
        return redirect(route('post.index'))->with('msg', 'Post is removed successfully!');
    }
}

resources/views/post/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">

                @include('partials.error')
                @include('partials.msg')
                <ul class="breadcrumb">
                    <li><a href="{{ route('home') }}">Home</a></li>
                    <li><a href="{{ route('post.index') }}">Post</a></li>
                    <li class="active">New</li>
                </ul>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            Post
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('post.store') }}" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="category_id" class="col-md-2 control-label">Category</label>

                                <div class="col-md-10">
                                    <?php $rows = $categories; ?>
                                    <select name="category_id" id="category_id" class="form-control">
                                        @foreach($rows as $row)
                                            <option value="{{ $row->id }}"{{ $row->id == old('category_id') ? ' selected' : '' }}>{{ $row->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="title" class="col-md-2 control-label">Title</label>

                                <div class="col-md-10">
                                    <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}" required>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="excerpt" class="col-md-2 control-label">Excerpt</label>

                                <div class="col-md-10">
                                    <textarea name="excerpt" id="excerpt" rows="5" class="form-control">{{ old('excerpt') }}</textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="thumbnail" class="col-md-2 control-label">Upload Thumbnail</label>

                                <div class="col-md-10">
                                    <input type="file" name="thumbnail" class="form-control" id="thumbnail">
                                    <small>Thumbnail size: 40 X 40</small>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="content" class="col-md-2 control-label">Content</label>

                                <div class="col-md-10">
                                    <textarea name="content" id="content" rows="10" class="form-control">{!! old('content') !!}</textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10 col-md-offset-2">
                                    <button type="submit" class="btn btn-primary">
                                        Save
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src='//cdn.tinymce.com/4/tinymce.min.js'></script>

    <script>
        tinymce.init({
            selector: '#content',
            height: 500,
            theme: 'modern',
            plugins: [
                'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons template paste textcolor colorpicker textpattern imagetools codesample'
            ],
            toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
            toolbar2: 'print preview media | forecolor backcolor emoticons | codesample',
            image_advtab: true,
            templates: [

            ],
            content_css: [
                '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
                '//www.tinymce.com/css/codepen.min.css'
            ]
        });
    </script>

@endsection

resources/views/post/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">

                @include('partials.error')
                @include('partials.msg')
                <ul class="breadcrumb">
                    <li><a href="{{ route('home') }}">Home</a></li>
                    <li><a href="{{ route('post.index') }}">Post</a></li>
                    <li class="active">Edit</li>
                </ul>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            Post Edit
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('post.update', $row->id) }}" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}

                            <div class="form-group">
                                <label for="category_id" class="col-md-2 control-label">Category</label>

                                <div class="col-md-10">
                                    <select name="category_id" id="category_id" class="form-control">
                                        @foreach($categories as $category)
                                            <option value="{{ $category->id }}"{{ $category->id == $row->category_id ? ' selected' : '' }}>{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="title" class="col-md-2 control-label">Title</label>

                                <div class="col-md-10">
                                    <input id="title" type="text" class="form-control" name="title" value="{{ $row->title }}" required>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="excerpt" class="col-md-2 control-label">Excerpt</label>

                                <div class="col-md-10">
                                    <textarea name="excerpt" id="excerpt" rows="5" class="form-control">{{ $row->excerpt }}</textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="thumbnail" class="col-md-2 control-label">Upload Thumbnail</label>

                                <div class="col-md-5">
                                    <img src="{{ url($row->thumbnail) }}" alt="" class="img-responsive">
                                </div>

                                <div class="col-md-5">
                                    <input type="file" name="thumbnail" class="form-control" id="thumbnail">
                                    <small>Thumbnail size: 40 X 40</small>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="content" class="col-md-2 control-label">Content</label>

                                <div class="col-md-10">
                                    <textarea name="content" id="content" rows="10" class="form-control">{!! $row->content !!}</textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10 col-md-offset-2">
                                    <button type="submit" class="btn btn-primary">
                                        Update
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src='//cdn.tinymce.com/4/tinymce.min.js'></script>

    <script>
        tinymce.init({
            selector: '#content',
            height: 500,
            theme: 'modern',
            plugins: [
                'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons template paste textcolor colorpicker textpattern imagetools codesample'
            ],
            toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
            toolbar2: 'print preview media | forecolor backcolor emoticons | codesample',
            image_advtab: true,
            templates: [

            ],
            content_css: [
                '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
                '//www.tinymce.com/css/codepen.min.css'
            ]
        });
    </script>

@endsection

resources/views/post/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                @include('partials.error')
                @include('partials.msg')
                <ul class="breadcrumb">
                    <li><a href="{{ route('home') }}">Home</a></li>
                    <li class="active">All Posts</li>
                </ul>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            Post List
                        </div>
                        <div class="pull-right">
                            <a href="{{ route('post.create') }}" class="btn btn-primary btn-xs">Create New</a>
                        </div>
                        <div class="clearfix"></div>
                    </div>

                    <div class="panel-heading">
                        <form action="" method="get">
                            <div class="form-group">
                                <label for="category_id" class="col-md-2 control-label">Category</label>

                                <div class="col-md-6">
                                    <select name="category_id" id="category_id" class="form-control input-sm">
                                        <option value="all">All</option>
                                        @foreach($categories as $category)
                                            <option value="{{ $category->id }}"{{ $category->id == request('category_id') ? ' selected' : '' }}>{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-md-4">
                                    <input type="submit" value="Show" class="btn btn-primary btn-sm">
                                </div>
                            </div>
                        </form>
                        <div class="clearfix"></div>
                    </div>

                    <div class="panel-body table-responsive">
                        <table class="table table-striped table-hover ">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Thumbnail</th>
                                    <th>Title</th>
                                    <th>Category</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $index = 0; ?>
                                @foreach($rows as $row)
                                    <tr>
                                        <td>{{ ++$index }}</td>
                                        <td><img src="{{ url($row->thumbnail) }}" alt="" class="img-responsive" style="max-width: 40px;"></td>
                                        <td>{{ $row->title }}</td>
                                        <td>{{ $row->category->name }}</td>
                                        <td>
                                            <a href="{{ route('post.edit', ['id'=>$row->id]) }}" class="btn btn-primary btn-xs">Edit</a>
                                            <a href="{{ route('post.delete', ['id'=>$row->id]) }}" class="btn btn-danger btn-xs" onclick="return confirm('Are you sure want to remove this?')">Remove</a>
                                        </td>
                                    </tr>
                                @endforeach

                                @if($rows->total() == 0)
                                    <tr>
                                        <td colspan="5">No data found!</td>
                                    </tr>
                                @endif

                            </tbody>
                        </table>

                        {!! $rows->render() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection