routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes();

Route::get('/home', ['as'=>'home', 'uses'=>'HomeController@index']);

Route::group(['middleware'=>['auth']], function(){
    Route::resource('category', 'CategoryController');
    Route::get('category/{id}/delete', ['as'=>'category.delete', 'uses'=>'CategoryController@destroy']);

    Route::resource('post', 'PostController');
    Route::get('post/{id}/delete', ['as'=>'post.delete', 'uses'=>'PostController@destroy']);

    Route::resource('media', 'MediaController');
    Route::get('media/{id}/delete', ['as'=>'media.delete', 'uses'=>'MediaController@destroy']);

});

app/Models/Media.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Media extends Model
{
    protected $table = 'medias';
    
    protected $fillable = ['name', 'link'];
}

app/Http/Controllers/MediaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Media;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class MediaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rows = Media::orderBy('id', 'desc')->paginate(10);
        return view('media.index', ['rows'=>$rows]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('media.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'  =>  'required|max:255|string',
            'file'  =>  'required|image'
        ]);

        $fileName = str_random(16) . time() .  '.' . $request->file('file')->getClientOriginalExtension();
        $request->file('file')->move('uploads', $fileName);
        $filePath = 'uploads/' . $fileName;

        Media::create([
            'name'  =>  $request->name,
            'link'  =>  $filePath
        ]);

        return redirect(route('media.index'))->with('msg', 'Media is created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $row = Media::find($id);
        return view('media.edit', ['row'=>$row]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name'  =>  'required|max:255|string',
            'file'  =>  'image'
        ]);

        $media = Media::find($id);

        if($request->hasFile('file')){
            $fileName = str_random(16) . time() .  '.' . $request->file('file')->getClientOriginalExtension();
            $request->file('file')->move('uploads', $fileName);
            $filePath = 'uploads/' . $fileName;
        }else{
            $filePath = $media->link;
        }


        $media->update([
            'name'  =>  $request->name,
            'link'  =>  $filePath
        ]);

        return redirect(route('media.index'))->with('msg', 'Media is updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $media = Media::find($id);
        File::delete($media->link);
        Media::destroy($id);
        return redirect(route('media.index'))->with('msg', 'Media is removed successfully!');
    }
}

resources/views/media/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                @include('partials.error')
                @include('partials.msg')
                <ul class="breadcrumb">
                    <li><a href="{{ route('home') }}">Home</a></li>
                    <li><a href="{{ route('media.index') }}">Media</a></li>
                    <li class="active">New</li>
                </ul>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            Media
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('media.store') }}" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="name" class="col-md-4 control-label">Name / Title</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="file" class="col-md-4 control-label">Upload file</label>

                                <div class="col-md-6">
                                    <input id="file" type="file" class="form-control" name="file">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Save
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/media/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                @include('partials.error')
                @include('partials.msg')
                <ul class="breadcrumb">
                    <li><a href="{{ route('home') }}">Home</a></li>
                    <li><a href="{{ route('media.index') }}">Media</a></li>
                    <li class="active">Edit</li>
                </ul>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            Edit Media
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('media.update', $row->id) }}" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}

                            <div class="form-group">
                                <label for="name" class="col-md-2 control-label">Category name</label>

                                <div class="col-md-8">
                                    <input id="name" type="text" class="form-control" name="name" value="{{ $row->name }}" required autofocus>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="file" class="col-md-2 control-label">Upload file</label>

                                <div class="col-md-4">
                                    <img src="{{ url($row->link) }}" alt="" class="img-responsive">
                                </div>

                                <div class="col-md-4">
                                    <input id="file" type="file" class="form-control" name="file">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10 col-md-offset-2">
                                    <button type="submit" class="btn btn-primary">
                                        Update
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/media/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                @include('partials.error')
                @include('partials.msg')
                <ul class="breadcrumb">
                    <li><a href="{{ route('home') }}">Home</a></li>
                    <li class="active">All Medias</li>
                </ul>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="pull-left">
                            Media List
                        </div>
                        <div class="pull-right">
                            <a href="{{ route('media.create') }}" class="btn btn-primary btn-xs">Create New</a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body table-responsive">
                        <table class="table table-striped table-hover ">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Copy link</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $index = 0; ?>
                                @foreach($rows as $row)
                                    <tr>
                                        <td>{{ ++$index }}</td>
                                        <td>{{ $row->name }}</td>
                                        <td> <button class="btn btn-info btn-xs copy_link" data-clipboard-text="{{ $row->link }}">Copy link</button> </td>
                                        <td>
                                            <a href="{{ route('media.edit', ['id'=>$row->id]) }}" class="btn btn-primary btn-xs">Edit</a>
                                            <a href="{{ route('media.delete', ['id'=>$row->id]) }}" class="btn btn-danger btn-xs" onclick="return confirm('Are you sure want to remove this?')">Remove</a>
                                        </td>
                                    </tr>
                                @endforeach

                                @if($rows->total() == 0)
                                    <tr>
                                        <td colspan="4">No data found!</td>
                                    </tr>
                                @endif

                            </tbody>
                        </table>

                        {!! $rows->render() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.13/clipboard.min.js"></script>
    <script type="text/javascript">
        var clipboard = new Clipboard('.copy_link');

        clipboard.on('success', function(e) {
            e.trigger.innerHTML = 'Copied';
            e.trigger.className = 'btn btn-success btn-xs';
            setTimeout(function(){
                e.trigger.innerHTML = 'Copy link';
                e.trigger.className = 'btn btn-info btn-xs';
            }, 2000);
        });

    </script>
@endsection